### ISSUE TITLE
How to achieve thread safety?

### ISSUE THREAD

**Issue by sartak** [tsurai/mecab-rs#10]
Hi, thanks for mecab-rs.

https://github.com/tsurai/mecab-rs#multithreaded-environment does not actually use threads, and it's not clear to me how it could, since none of the objects involved (Model, Tagger, Lattice) are Send or Sync.

To reproduce, take the example code and as it suggests with the "create lattice object per thread" comment, wrap everything below `let tagger = model.create_tagger();` in a `std::thread::spawn(|| { … }).join().unwrap();`

```rust
    // create model object
    let model = Model::new("");

    // create tagger based on the model
    let tagger = model.create_tagger();

    std::thread::spawn(|| {
        // create lattice object per thread
        let mut lattice = model.create_lattice();
    …
            println!("rsize: {}", dict.rsize);
            println!("version: {}", dict.version);
        }
    })
    .join()
    .unwrap();
```

The compile errors you get look like:

```
error[E0277]: `*mut c_void` cannot be shared between threads safely
   --> src/main.rs:12:24
    |
12  |       std::thread::spawn(|| {
    |  _____------------------_^
    | |     |
    | |     required by a bound introduced by this call
13  | |         // create lattice object per thread
14  | |         let mut lattice = model.create_lattice();
15  | |
...   |
114 | |         }
115 | |     })
    | |_____^ `*mut c_void` cannot be shared between threads safely
    |
    = help: within `Model`, the trait `Sync` is not implemented for `*mut c_void`
```

Seemingly the only way to use mecab-rs in a multithreaded environment is to initialize the entire tree of objects from scratch in every thread (which involves reloading the dictionary every time). Is that the recommended approach?

**Comment by tsurai** [comment]
Hi, good that you remind me of this. I had `Send` and `Sync` implemented for the `Model` for a while on my local version but forgot to actually push it. The [multithreaded example](https://github.com/tsurai/mecab-rs/blob/master/examples/multithreaded.rs) has been updated as well.

Keep in mind that the thread safety relies purely on the promises of the underlying C mecab library.

**Comment by sartak** [comment]
Excellent, thank you!
