### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by equal-l2** [tsurai/mecab-rs#6]
On 0.1.3, `mecab::Tagger::parse_str` will SEGV on macOS.
(This is fixed with 508dd5d891b401124cedf376bc07e63f8f2f22dd)

**Comment by tsurai** [comment]
Hi,
thanks for making me aware of this issue. Somehow I've forgotten to actually push the changes from github to crates.io.
The version has been bumped and uploaded to crates.io.
