### ISSUE TITLE
Is Tagger  Sync and Send?

### ISSUE THREAD

**Issue by sirodeneko** [tsurai/mecab-rs#8]
Are Tagger objects thread safe? 
If yes, hope to add
```
unsafe impl Send for Tagger {}
unsafe impl Sync for Tagger {}
```

**Comment by tsurai** [comment]
No, `Tagger` is not thread safe as it utilizes internal mutable raw pointer. In a multithreaded environment multiple `Tagger` objects would access the same `Model` but there is no guarantee that the `Model` won't go out of scope and cause a memory violation for the `Tagger`.

What I could do is implement Send and Sync for `Model` instead:

```rust
let model = Arc::new(Model::new(""));                                                            

for _ in 0..2 {
  let model = model.clone();
  thread::spawn(move || {
    let mut lattice = model.create_lattice();
    let mut tagger = model.create_tagger();
    // [...]
  });
}
```

**Comment by sirodeneko** [comment]
I create Model and Tagger in single thread, use `parse` in `tokio sync` .Is this safe？
```
struct MyModel {
    m: Model,
    t: Tagger,

}
unsafe impl Send for MyModel {}
unsafe impl Sync for MyModel {}

impl MyModel {
    fn new(dictionary: &String) -> Self {
        let m = Model::new();
        let t = m.create_tagger();
        Self {
            m,
            t,
        }
    }
    fn parse_str(&self, s: &str) -> String {
        let mut lattice = self.m.create_lattice();
        lattice.set_sentence(s);
        self.t.parse(&lattice);
        lattice.to_string()
    }
}

// Because it is used in tokio, RsMeCab must implement Send + Sync
struct RsMeCab {
    model: Arc<MyModel>,
    ...
}
// ----- Multithreaded asynchronous environment---------
impl  RsMeCab {
    fn xxxx(&self, s:&str){
         self.parse_str(s);
    }
}

```

**Comment by tsurai** [comment]
Yes that would work since `Model` and `Tagger` have the same lifetime via `MyModel`. That being said `Model` uses a lot of memory and it might not be adviced to have one per thread.

**Comment by sirodeneko** [comment]
Yes, because it may use a lot of memory, in practice MyModel will only be created once, and then multiple RsMeCabs will only have a single reference to `Arc<MyModel>`.
